[2024-10-03T13:10:04.699+0000] {processor.py:186} INFO - Started process (PID=72) to work on /opt/airflow/dags/dag.py
[2024-10-03T13:10:04.701+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-03T13:10:04.707+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:10:04.707+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-03T13:10:04.945+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:10:04.769+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from ETL.extract.multi_threading import MultiThreading
  File "/opt/airflow/dags/ETL/extract/multi_threading.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-10-03T13:10:05.049+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-03T13:10:05.221+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.533 seconds
[2024-10-03T13:10:35.726+0000] {processor.py:186} INFO - Started process (PID=135) to work on /opt/airflow/dags/dag.py
[2024-10-03T13:10:36.088+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-03T13:10:36.092+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:10:36.092+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-03T13:10:36.590+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:10:36.542+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from ETL.extract.multi_threading import MultiThreading
  File "/opt/airflow/dags/ETL/extract/multi_threading.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-10-03T13:10:36.606+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-03T13:10:36.742+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 1.029 seconds
[2024-10-03T13:11:07.280+0000] {processor.py:186} INFO - Started process (PID=198) to work on /opt/airflow/dags/dag.py
[2024-10-03T13:11:07.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-03T13:11:07.284+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:11:07.284+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-03T13:11:07.795+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:11:07.720+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from ETL.extract.multi_threading import MultiThreading
  File "/opt/airflow/dags/ETL/extract/multi_threading.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-10-03T13:11:07.798+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-03T13:11:08.028+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.757 seconds
[2024-10-03T13:11:38.543+0000] {processor.py:186} INFO - Started process (PID=262) to work on /opt/airflow/dags/dag.py
[2024-10-03T13:11:38.547+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-03T13:11:38.552+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:11:38.551+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-03T13:11:38.657+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:11:38.641+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from ETL.extract.multi_threading import MultiThreading
  File "/opt/airflow/dags/ETL/extract/multi_threading.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-10-03T13:11:38.662+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-03T13:11:38.838+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.310 seconds
[2024-10-03T13:12:09.761+0000] {processor.py:186} INFO - Started process (PID=323) to work on /opt/airflow/dags/dag.py
[2024-10-03T13:12:09.763+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-03T13:12:09.768+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:12:09.767+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-03T13:12:09.858+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:12:09.848+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from ETL.extract.multi_threading import MultiThreading
  File "/opt/airflow/dags/ETL/extract/multi_threading.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-10-03T13:12:09.862+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-03T13:12:09.992+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.243 seconds
[2024-10-03T13:12:40.137+0000] {processor.py:186} INFO - Started process (PID=386) to work on /opt/airflow/dags/dag.py
[2024-10-03T13:12:40.143+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-03T13:12:40.150+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:12:40.148+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-03T13:12:40.238+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:12:40.225+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from ETL.extract.multi_threading import MultiThreading
  File "/opt/airflow/dags/ETL/extract/multi_threading.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-10-03T13:12:40.244+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-03T13:12:40.748+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.623 seconds
[2024-10-03T13:13:10.959+0000] {processor.py:186} INFO - Started process (PID=449) to work on /opt/airflow/dags/dag.py
[2024-10-03T13:13:10.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-03T13:13:10.962+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:13:10.962+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-03T13:13:11.021+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:13:11.013+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from ETL.extract.multi_threading import MultiThreading
  File "/opt/airflow/dags/ETL/extract/multi_threading.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-10-03T13:13:11.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-03T13:13:11.262+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.311 seconds
[2024-10-03T13:13:41.941+0000] {processor.py:186} INFO - Started process (PID=512) to work on /opt/airflow/dags/dag.py
[2024-10-03T13:13:41.943+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-03T13:13:41.947+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:13:41.947+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-03T13:13:42.511+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:13:42.267+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from ETL.extract.multi_threading import MultiThreading
  File "/opt/airflow/dags/ETL/extract/multi_threading.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-10-03T13:13:42.515+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-03T13:13:43.049+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 1.118 seconds
[2024-10-03T13:14:13.714+0000] {processor.py:186} INFO - Started process (PID=575) to work on /opt/airflow/dags/dag.py
[2024-10-03T13:14:13.717+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-03T13:14:13.720+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:14:13.719+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-03T13:14:13.809+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:14:13.790+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from ETL.extract.multi_threading import MultiThreading
  File "/opt/airflow/dags/ETL/extract/multi_threading.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-10-03T13:14:13.814+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-03T13:14:14.383+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.684 seconds
[2024-10-03T13:14:44.730+0000] {processor.py:186} INFO - Started process (PID=634) to work on /opt/airflow/dags/dag.py
[2024-10-03T13:14:44.732+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-03T13:14:44.735+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:14:44.734+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-03T13:14:44.812+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:14:44.800+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from ETL.extract.multi_threading import MultiThreading
  File "/opt/airflow/dags/ETL/extract/multi_threading.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-10-03T13:14:44.815+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-03T13:14:45.050+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.327 seconds
[2024-10-03T13:15:15.432+0000] {processor.py:186} INFO - Started process (PID=697) to work on /opt/airflow/dags/dag.py
[2024-10-03T13:15:15.433+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-03T13:15:15.437+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:15:15.436+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-03T13:15:15.679+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:15:15.663+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from ETL.extract.multi_threading import MultiThreading
  File "/opt/airflow/dags/ETL/extract/multi_threading.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-10-03T13:15:15.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-03T13:15:15.777+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.354 seconds
[2024-10-03T13:15:45.909+0000] {processor.py:186} INFO - Started process (PID=756) to work on /opt/airflow/dags/dag.py
[2024-10-03T13:15:45.918+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-03T13:15:45.924+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:15:45.924+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-03T13:15:45.995+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:15:45.987+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from ETL.extract.multi_threading import MultiThreading
  File "/opt/airflow/dags/ETL/extract/multi_threading.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-10-03T13:15:45.998+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-03T13:15:46.173+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.276 seconds
[2024-10-03T13:16:16.431+0000] {processor.py:186} INFO - Started process (PID=818) to work on /opt/airflow/dags/dag.py
[2024-10-03T13:16:16.433+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-03T13:16:16.437+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:16:16.436+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-03T13:16:16.538+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:16:16.522+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from ETL.extract.multi_threading import MultiThreading
  File "/opt/airflow/dags/ETL/extract/multi_threading.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-10-03T13:16:16.547+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-03T13:16:16.656+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.235 seconds
[2024-10-03T13:16:47.238+0000] {processor.py:186} INFO - Started process (PID=879) to work on /opt/airflow/dags/dag.py
[2024-10-03T13:16:47.239+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-03T13:16:47.245+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:16:47.244+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-03T13:16:47.298+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:16:47.290+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from ETL.extract.multi_threading import MultiThreading
  File "/opt/airflow/dags/ETL/extract/multi_threading.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-10-03T13:16:47.301+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-03T13:16:47.373+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.142 seconds
[2024-10-03T13:17:17.959+0000] {processor.py:186} INFO - Started process (PID=942) to work on /opt/airflow/dags/dag.py
[2024-10-03T13:17:17.960+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-03T13:17:17.969+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:17:17.968+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-03T13:17:18.091+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:17:18.071+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from ETL.extract.multi_threading import MultiThreading
  File "/opt/airflow/dags/ETL/extract/multi_threading.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-10-03T13:17:18.099+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-03T13:17:18.205+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.261 seconds
[2024-10-03T13:17:48.412+0000] {processor.py:186} INFO - Started process (PID=1005) to work on /opt/airflow/dags/dag.py
[2024-10-03T13:17:48.414+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-03T13:17:48.417+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:17:48.417+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-03T13:17:48.489+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:17:48.479+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from ETL.extract.multi_threading import MultiThreading
  File "/opt/airflow/dags/ETL/extract/multi_threading.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-10-03T13:17:48.493+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-03T13:17:48.563+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.159 seconds
[2024-10-03T13:18:19.844+0000] {processor.py:186} INFO - Started process (PID=1062) to work on /opt/airflow/dags/dag.py
[2024-10-03T13:18:19.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag.py for tasks to queue
[2024-10-03T13:18:19.848+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:18:19.848+0000] {dagbag.py:587} INFO - Filling up the DagBag from /opt/airflow/dags/dag.py
[2024-10-03T13:18:19.920+0000] {logging_mixin.py:190} INFO - [2024-10-03T13:18:19.912+0000] {dagbag.py:386} ERROR - Failed to import: /opt/airflow/dags/dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 382, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag.py", line 6, in <module>
    from ETL.extract.multi_threading import MultiThreading
  File "/opt/airflow/dags/ETL/extract/multi_threading.py", line 3, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'
[2024-10-03T13:18:19.923+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag.py
[2024-10-03T13:18:20.042+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag.py took 0.204 seconds
